name: Validate Pull Request Metadata

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  jack-compiler-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - working-directory: ./jack_compiler
        run: |
          bundle install
          bundle exec rake

      - name: Unit tests for the Jack Compiler
        working-directory: ./jack_compiler
        run: |
          bundle exec rspec

  trailing-whitespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: ofer987/me-not-whitespace@v4
        with:
          BASE_REF: ${{ github.base_ref }}
